# shellcheck shell=bash
# set -euo pipefail
# IFS=$'\n\t'

export LC_ALL=en_US.UTF-8
export EDITOR=nvim
# History
export HISTSIZE=
export HISTFILESIZE=
export HISTTIMEFORMAT="[%F %T] "
export HISTFILE=~/.all_history
# append to history file instead of overwriting
shopt -s histappend
# A new shell gets the history lines from all previous shells
PROMPT_COMMAND='history -a'
# Don't put duplicate lines in the history.
export HISTCONTROL=ignoredups

# Completiuons and integrations (moved from profile)

[[ -r "/opt/homebrew/bin/brew" ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

# bash completions
export BASH_COMPLETION_COMPAT_DIR="/opt/homebrew/etc/bash_completion.d"
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

# bash completion for git on mac:
# shellcheck source=/Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash
[[ which xcode-select ]] && . "$(xcode-select -p)/usr/share/git-core/git-completion.bash"

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"

export PATH="${HOME}/.local/bin:${PATH}"
eval "$(~/.local/bin/mise activate bash --shims)"
eval "$(~/.local/bin/mise completion bash)"


function parse_git_dirty {
  [[ $(git status --porcelain 2>/dev/null) ]] && echo "*"
}

# PROMPT_COMMAND='PS1_CMD1=$(git branch --show-current 2>/dev/null)'; PS1='\[\e[38;5;197m\]\u\[\e[0m\]@\[\e[38;5;37m\]\h\[\e[0m\] \[\e[38;5;45m\]\w\[\e[0m\] \[\e[38;5;40m\]${PS1_CMD1}\[\e[0m\] >'
# from https://bash-prompt-generator.org/

if [[ -n $(which vivid) ]]; then
  LS_COLORS=$(vivid generate molokai)
  export LS_COLORS
fi
# this silliness is useless unless we enable the --color option for ls:
alias ls="ls --color=auto"

alias lv="env NVIM_APPNAME=lazyvim nvim"
alias nv25="env NVIM_APPNAME=nvim_2025 nvim"
function go_to_project() {
  PROJECTS="$HOME/Documents/code"
  dir=$(fd . "$PROJECTS" --type d --max-depth 1 -exec basename {} \; | fzf --multi --tmux=center) &&
    cd "$PROJECTS/${dir}" || return
}
alias p="go_to_project"

eval "$(starship init bash)"
