# shellcheck shell=bash
# set -euo pipefail
# IFS=$'\n\t'

export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export EDITOR=nvim
# History
export HISTSIZE=
export HISTFILESIZE=
export HISTTIMEFORMAT="[%F %T] "
export HISTFILE=~/.all_history
# append to history file instead of overwriting
shopt -s histappend
# A new shell gets the history lines from all previous shells
PROMPT_COMMAND='history -a'
# Don't put duplicate lines in the history.
export HISTCONTROL=ignoredups

# PATH stuff

# MACOS Applications
[[ -d "${HOME}"/.antigravity/antigravity/bin &&
  "$PATH" != *antigravity/antigravity/bin* ]] &&
  export PATH="$PATH:${HOME}/.antigravity/antigravity/bin"

[[ -d /Applications/Obsidian.app/Contents/MacOS &&
  "$PATH" != */Applications/Obsidian.app/Contents/MacOS* ]] &&
  export PATH="$PATH:/Applications/Obsidian.app/Contents/MacOS"

# Personal bin/ directory
export PATH="${HOME}/.local/bin:${PATH}"

alias ls="ls --color=auto"

export NVIM_APPNAME="lazyvim" # alternatives: astrovim, nvim_2025
alias lv="env NVIM_APPNAME=lazyvim nvim"

function go_to_project() {
  PROJECTS="$HOME/Documents/code"
  dir=$(fd . "$PROJECTS" --type d --max-depth 1 --exec basename {} \; | fzf --multi --tmux=center) &&
    cd "$PROJECTS/${dir}" || return
}

# Aliases
alias p="go_to_project"
alias s="starship toggle line_break"
# peon-ping quick controls
alias peon="bash \$HOME/.claude/hooks/peon-ping/peon.sh"

eval "$(~/.local/bin/mise activate bash)"
[[ -r "/opt/homebrew/bin/brew" ]] && eval "$(/opt/homebrew/bin/brew shellenv)"
# bash completions
[[ -d "/opt/homebrew/etc/bash_completion.d" ]] && export BASH_COMPLETION_COMPAT_DIR="/opt/homebrew/etc/bash_completion.d"
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"
# bash completion for git on mac:
# shellcheck source=/Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash
which xcode-select >&/dev/null && . "$(xcode-select -p)/usr/share/git-core/git-completion.bash"

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"
. "${HOME}/.local/bin/fzf-git.sh" # git fzf integration

# mise completion
eval "$(~/.local/bin/mise completion bash)"
eval "$(starship init bash)"
[ -f "$HOME/.claude/hooks/peon-ping/completions.bash" ] && source "$HOME/.claude/hooks/peon-ping/completions.bash"
