# shellcheck shell=bash
# set -euo pipefail
# IFS=$'\n\t'

export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export EDITOR=nvim
# History
export HISTSIZE=
export HISTFILESIZE=
export HISTTIMEFORMAT="[%F %T] "
export HISTFILE=~/.all_history
# append to history file instead of overwriting
shopt -s histappend
# A new shell gets the history lines from all previous shells
PROMPT_COMMAND='history -a'
# Don't put duplicate lines in the history.
export HISTCONTROL=ignoredups

# PATH stuff

export PATH="${HOME}/.local/bin:${PATH}"
eval "$(~/.local/bin/mise activate bash --shims)"

# Completiuons and integrations (moved from profile)

[[ -r "/opt/homebrew/bin/brew" ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

# bash completions
export BASH_COMPLETION_COMPAT_DIR="/opt/homebrew/etc/bash_completion.d"
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

# bash completion for git on mac:
# shellcheck source=/Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash
which xcode-select >&/dev/null && . "$(xcode-select -p)/usr/share/git-core/git-completion.bash"

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"

# mise completion
eval "$(~/.local/bin/mise completion bash)"

alias ls="ls --color=auto"

export NVIM_APPNAME="lazyvim" # alternatives: astrovim, nvim_2025
alias lv="env NVIM_APPNAME=lazyvim nvim"

function go_to_project() {
  PROJECTS="$HOME/Documents/code"
  dir=$(fd . "$PROJECTS" --type d --max-depth 1 --exec basename {} \; | fzf --multi --tmux=center) &&
    cd "$PROJECTS/${dir}" || return
}
alias p="go_to_project"

eval "$(starship init bash)"
alias s="starship toggle line_break"

# peon-ping quick controls
alias peon="bash ~/.claude/hooks/peon-ping/peon.sh"
[ -f ~/.claude/hooks/peon-ping/completions.bash ] && source ~/.claude/hooks/peon-ping/completions.bash
