[settings]
env_cache = true
hook_env.chpwd_only = true
prefer_offline = true

[tools]
# hadolint = "latest"
"github:HalFrgrd/flyline" = "latest"
"npm:@mariozechner/gccli" = "0.1.2"
"npm:@mariozechner/gdcli" = "0.1.1"
"npm:@mariozechner/gmcli" = "0.2.0"
"npm:defuddle" = "0.19.2"
claude = "2.1.272"
codex = "0.154.0"
fd = "10.5.0"
fzf = "0.74.4"
gh = "2.100.0"
herdr = "0.9.0"
jq = "1.8.2"
node = "26.8.2"
perl = "5.44.0.0"
pi = "0.85.1"
python = "3.14.7"
ripgrep = "15.2.0"
shellcheck = "0.11.0"
starship = "1.26.0"
usage = "6.9.1"
yt-dlp = "latest"

