[settings]
env_cache = true
hook_env.chpwd_only = true

[tools]
# hadolint = "latest"
"github:HalFrgrd/flyline" = "latest"
"npm:@mariozechner/gccli" = "0.1.2"
"npm:@mariozechner/gdcli" = "0.1.1"
"npm:@mariozechner/gmcli" = "0.2.0"
"npm:defuddle" = "0.19.2"
claude = "2.1.231"
codex = "0.147.0"
fd = "10.4.2"
fzf = "0.74.2"
gh = "2.97.0"
herdr = "0.8.0"
jq = "1.8.2"
node = "26.7.0"
perl = "5.44.0.0"
pi = "0.84.1"
python = "3.14.7"
ripgrep = "15.2.0"
shellcheck = "0.11.0"
starship = "1.26.0"
usage = "5.1.0"
yt-dlp = "latest"

